In [ ]:
!pip install yfinance

In [ ]:
import pandas as pd
import yfinance as yf

In [ ]:
df = yf.download( "TSLA", period='5y')

/tmp/ipykernel_3338/1122126556.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download( "TSLA", period='5y')
[*********************100%***********************]  1 of 1 completed


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [ ]:
!pip install tensorflow
import tensorflow as tf
from tensorflow import keras

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1255 entries, 2021-05-24 to 2026-05-21
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   (Close, TSLA)   1255 non-null   float64
 1   (High, TSLA)    1255 non-null   float64
 2   (Low, TSLA)     1255 non-null   float64
 3   (Open, TSLA)    1255 non-null   float64
 4   (Volume, TSLA)  1255 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 58.8 KB


In [ ]:
train_length = round(len(df)*0.7)
lg = len(df)
val_length = lg-train_length

print('Total observations:',lg)
print('Training set:', train_length)
print('Validation set:', val_length)


Total observations: 1255
Training set: 878
Validation set: 377


In [ ]:
train_data = df[('Close', 'TSLA')][:train_length]
val_data = df[('Close', 'TSLA')][train_length:]

In [ ]:
train=train_data.values.reshape(-1,1)
train

array([[202.14666748],
       [201.56333923],
       [206.37666321],
       [210.28334045],
       [208.40666199],
       [207.96665955],
       [201.70666504],
       [190.94667053],
       [199.68333435],
       [201.71000671],
       [201.19667053],
       [199.59333801],
       [203.37333679],
       [203.29666138],
       [205.89666748],
       [199.78666687],
       [201.62333679],
       [205.53334045],
       [207.77000427],
       [206.94332886],
       [207.90333557],
       [218.85667419],
       [226.60667419],
       [223.95666504],
       [229.57333374],
       [226.91999817],
       [226.56666565],
       [225.97332764],
       [226.30000305],
       [219.86000061],
       [214.8833313 ],
       [217.60333252],
       [218.9833374 ],
       [228.56666565],
       [222.84666443],
       [217.79333496],
       [216.8666687 ],
       [214.74000549],
       [215.40666199],
       [220.16667175],
       [218.42999268],
       [216.41999817],
       [214.46000671],
       [219

In [ ]:
scaler = MinMaxScaler()
scaled_trainset = scaler.fit_transform(train)

In [ ]:
x_train = []
y_train = []
step = 50

for i in range(step, train_length):
    x_train.append(scaled_trainset[i-step:i,0])
    y_train.append(scaled_trainset[i,0])

In [ ]:
X_train, y_train = np.array(x_train), np.array(y_train)

In [ ]:
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
y_train.reshape(y_train.shape[0],1)

array([[0.42691665],
       [0.43101337],
       [0.41386471],
       [0.43005267],
       [0.42588972],
       [0.42349357],
       [0.43942757],
       [0.43381811],
       [0.399587  ],
       [0.37699452],
       [0.40270093],
       [0.38556334],
       [0.39306101],
       [0.42181513],
       [0.42423338],
       [0.42722585],
       [0.4161394 ],
       [0.42802091],
       [0.44899021],
       [0.45430154],
       [0.45250164],
       [0.45062446],
       [0.45192742],
       [0.47329423],
       [0.47434324],
       [0.47543643],
       [0.45490887],
       [0.46234032],
       [0.46398559],
       [0.47650753],
       [0.47778846],
       [0.48054901],
       [0.44817305],
       [0.45834302],
       [0.4722121 ],
       [0.47408929],
       [0.49700204],
       [0.51574082],
       [0.50050246],
       [0.50464331],
       [0.49820568],
       [0.49791857],
       [0.50488624],
       [0.5038482 ],
       [0.50623333],
       [0.51822534],
       [0.50925891],
       [0.516

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN
from keras.layers import Dropout

In [ ]:
model = Sequential()

model.add(
    SimpleRNN(units = 50,return_sequences= True,input_shape = (X_train.shape[1],1)))

model.add(
    Dropout(0.2))

model.add(
    SimpleRNN(units = 50, return_sequences = True)
             )

model.add(
    Dropout(0.2)
             )

model.add(
    SimpleRNN(units = 50, return_sequences = True)
             )

model.add(
    Dropout(0.2)
             )

model.add(
    SimpleRNN(units = 50)
             )

model.add(
    Dropout(0.2)
             )

model.add(
    Dense(units = 1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

In [ ]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_20 (SimpleRNN)       │ (None, 50, 50)         │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 50, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_21 (SimpleRNN)       │ (None, 50, 50)         │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_21 (Dropout)            │ (None, 50, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_22 (SimpleRNN)       │ (None, 50, 50)         │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_22 (Dropout)            │ (None, 50, 50)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_23 (SimpleRNN)       │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_23 (Dropout)            │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,801 (69.54 KB)

 Trainable params: 17,801 (69.54 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X_train, y_train, epochs = 10, batch_size =16)

Epoch 1/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 21s 97ms/step - accuracy: 0.0012 - loss: 0.3321   
Epoch 2/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.0012 - loss: 0.2412
Epoch 3/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.0024 - loss: 0.1680    
Epoch 4/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - accuracy: 0.0024 - loss: 0.1166
Epoch 5/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - accuracy: 0.0000e+00 - loss: 0.0986
Epoch 6/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.0024 - loss: 0.0809
Epoch 7/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step - accuracy: 0.0024 - loss: 0.0657
Epoch 8/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.0024 - loss: 0.0655
Epoch 9/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.0024 - loss: 0.0585
Epoch 10/10
52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - accuracy: 0.0024 - loss: 0.0421    


In [ ]:
y_pred = model.predict(X_train)
y_pred = scaler.inverse_transform(y_pred.reshape(1,-1))

26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step


In [ ]:
X_train

array([[[0.31154692],
        [0.30961454],
        [0.32555956],
        ...,
        [0.40072437],
        [0.42553639],
        [0.42561368]],

       [[0.30961454],
        [0.32555956],
        [0.33850115],
        ...,
        [0.42553639],
        [0.42561368],
        [0.42691665]],

       [[0.32555956],
        [0.33850115],
        [0.3322843 ],
        ...,
        [0.42561368],
        [0.42691665],
        [0.43101337]],

       ...,

       [[0.3687349 ],
        [0.40437936],
        [0.33998077],
        ...,
        [0.70599927],
        [0.80133832],
        [0.73008245]],

       [[0.40437936],
        [0.33998077],
        [0.35833307],
        ...,
        [0.80133832],
        [0.73008245],
        [0.73587965]],

       [[0.33998077],
        [0.35833307],
        [0.39112863],
        ...,
        [0.73008245],
        [0.73587965],
        [0.6727399 ]]])

In [ ]:
y_train = scaler.inverse_transform(y_train.reshape(1,-1))
y_train

array([[236.97332764, 238.21000671, 233.03334045, 237.91999817,
        236.66333008, 235.94000244, 240.75      , 239.05667114,
        228.72332764, 221.90333557, 229.66333008, 224.49000549,
        226.75332642, 235.43333435, 236.16333008, 237.06666565,
        233.72000122, 237.30667114, 243.63667297, 245.24000549,
        244.69667053, 244.13000488, 244.52333069, 250.97332764,
        251.28999329, 251.61999512, 245.42333984, 247.66667175,
        248.16333008, 251.94332886, 252.33000183, 253.16333008,
        243.38999939, 246.46000671, 250.64666748, 251.21333313,
        258.13000488, 263.78668213, 259.18667603, 260.43667603,
        258.49334717, 258.40667725, 260.51000977, 260.19665527,
        260.91665649, 264.53668213, 261.82998657, 263.98001099,
        268.57333374, 270.35998535, 272.77334595, 281.01000977,
        290.03668213, 288.08999634, 288.6000061 , 298.        ,
        303.22665405, 341.61999512, 339.47665405, 345.95333862,
        359.01333618, 371.33334351, 402.

In [ ]:
y_train = scaler.inverse_transform(y_train.reshape(1,-1))
y_train

array([[ 71643.23906304,  72016.55537945,  70453.8751214 ,
         71929.0104992 ,  71549.66009917,  71331.30918349,
         72783.30315971,  72272.13797287,  69152.81154038,
         67094.06051685,  69436.57007995,  67874.89857328,
         68558.12726647,  71178.36128552,  71398.7250978 ,
         71671.41500919,  70661.1574089 ,  71743.86546807,
         73654.70313819,  74138.70113027,  73974.68460412,
         73803.62524297,  73922.35850501,  75869.41910149,
         75965.01096195,  76064.62861559,  74194.04427118,
         74871.23888077,  75021.16513076,  76162.23337265,
         76278.95834426,  76530.51514449,  73580.23978272,
         74506.98290211,  75770.81019922,  75941.86956037,
         78029.80528142,  79737.38645724,  78348.78260214,
         78726.12010557,  78139.48741804,  78113.32436849,
         78748.25736194,  78653.66504052,  78871.01181099,
         79963.7889593 ,  79146.71876418,  79795.74663996,
         81182.3329923 ,  81721.66951912,  82450.1906887

In [ ]:
y_train.shape
y_train = np.reshape(y_train, (828,1))

In [ ]:
y_pred.shape

(1, 828)

In [ ]:
y_pred.shape
y_pred = np.reshape(y_pred,(828,1))
y_pred

array([[236.63394 ],
       [240.49933 ],
       [246.40672 ],
       [251.87099 ],
       [256.1458  ],
       [254.34402 ],
       [255.34392 ],
       [256.0404  ],
       [255.37895 ],
       [254.1578  ],
       [250.19225 ],
       [247.619   ],
       [245.99625 ],
       [244.45573 ],
       [240.93633 ],
       [243.36307 ],
       [244.92546 ],
       [243.63618 ],
       [242.01373 ],
       [244.04347 ],
       [245.11603 ],
       [250.42673 ],
       [254.95082 ],
       [257.95813 ],
       [260.4771  ],
       [263.02283 ],
       [267.0851  ],
       [268.0752  ],
       [268.56708 ],
       [267.4033  ],
       [268.93234 ],
       [271.42004 ],
       [271.36078 ],
       [268.1665  ],
       [267.77466 ],
       [265.8046  ],
       [263.93347 ],
       [264.17654 ],
       [271.64932 ],
       [270.73132 ],
       [271.2448  ],
       [273.0878  ],
       [277.99915 ],
       [278.21808 ],
       [279.68842 ],
       [282.5851  ],
       [283.49774 ],
       [281.7

In [ ]:
val = val_data.values.reshape(-1,1)
val

array([[338.73999023],
       [346.        ],
       [342.02999878],
       [339.64001465],
       [352.55999756],
       [338.58999634],
       [338.23001099],
       [332.89001465],
       [345.16000366],
       [357.08999634],
       [351.42001343],
       [357.92999268],
       [369.48999023],
       [389.22000122],
       [389.79000854],
       [400.98999023],
       [424.76998901],
       [418.1000061 ],
       [436.23001099],
       [463.01998901],
       [479.85998535],
       [440.13000488],
       [436.17001343],
       [421.05999756],
       [430.6000061 ],
       [462.27999878],
       [454.13000488],
       [431.66000366],
       [417.41000366],
       [403.83999634],
       [379.27999878],
       [410.44000244],
       [411.04998779],
       [394.35998535],
       [394.94000244],
       [394.73999023],
       [403.30999756],
       [396.35998535],
       [428.22000122],
       [413.82000732],
       [426.5       ],
       [424.07000732],
       [415.10998535],
       [412

In [ ]:
scaled_valset = scaler.fit_transform(val)

In [ ]:
xval_train = []
yval_train = []
step = 50

for i in range(step, val_length):
    xval_train.append(scaled_valset[i-step:i,0])
    yval_train.append(scaled_valset[i,0])

In [ ]:
X_val, y_val = np.array(xval_train), np.array(yval_train)

In [ ]:
X_val = np.reshape(X_val, (X_val.shape[0],X_val.shape[1],1))  # reshape to 3D array
y_val = np.reshape(y_val, (-1,1))

In [ ]:
y_pred_val = model.predict(X_val)

11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


In [ ]:
y_val_is = scaler.inverse_transform(y_val)


In [ ]:
import tensorflow as tf
import os
from tensorflow.keras.models import load_model

In [ ]:
model.save(os.path.join('model', 'SimpleRNN_Forecasting.h5'))
new_model = load_model(os.path.join('model', 'SimpleRNN_Forecasting.h5'))